[package]
name = "led_raulette"
version = "0.1.0"
authors = ["Dheerajknoldus <dheeraj.mishra@knoldus.com>"]
edition = "2018"
[dependencies]
cortex-m = "0.6.4"
cortex-m-rt = "0.6.13"
stm32f3-discovery = "0.6.0"
panic-halt = "0.2.0"
panic-itm = "0.4.2"