[package]
name = "led_raulette"
version = "0.1.0"
authors = ["Dheerajknoldus <dheeraj.mishra@knoldus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aux5 = { path = "auxiliary" }